# --- Stage 1: Builder ---
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build


# --- Stage 2: Runtime ---
FROM node:20-alpine AS runner

WORKDIR /app

# Copy the built app from the builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.* ./

# Copy the environment file generated by the CI job
# This ensures secrets are only included in the final image layer
COPY .env.production .env.production

# Environment configuration
ENV NODE_ENV=production

# Expose default Next.js port
EXPOSE 3000

# Default command
CMD ["npm", "start"]
