name: Run on all Pushes
on:
  push:

jobs:
  determine-env:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Set environment
        id: set-env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "environment=Prod" >> $GITHUB_OUTPUT
          else
            echo "environment=Dev" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: determine-env
    name: Deploy with Terraform and Docker
    uses: ./.github/workflows/deploy.yml
    with:
      environment_variable: ${{ needs.determine-env.outputs.environment }}
    secrets: inherit